PRAGMA FOREIGN_KEYS = ON;
DROP TABLE regions;
CREATE TABLE regions(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

DROP TABLE cities;
CREATE TABLE cities(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  regions_id INTEGER NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  FOREIGN KEY(regions_id) REFERENCES regions(id)
);
